services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - type: bind
        source: ${PWD}/db
        target: /db
      - type: bind
        source: ${PWD}/scripts
        target: /scripts
