[project]
name = "vibe-check-api"
version = "0.1.0"
description = "An LLM-powered content moderation service built with FastAPI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dnspython>=2.7.0",
    "fastapi[standard]>=0.116.1",
    "pymongo>=4.14.0",
]
